# Generated by Django 4.2.1 on 2023-06-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=255)),
                ('contact', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('birth_date', models.DateField()),
                ('head', models.BooleanField()),
                ('function', models.CharField(max_length=50)),
                ('finger_print', models.ImageField(null=True, upload_to='finger_prints/')),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('attachment', models.FileField(null=True, upload_to='attachment/')),
                ('message_type', models.CharField(choices=[('AVISO', 'Aviso'), ('ATESTADO', 'Atestado'), ('JUSTIFICATIVA_DE_FALTA', 'Justificativa de falta'), ('DEMISSAO', 'Demissão'), ('PROMOCAO', 'Promoção'), ('OUTRO', 'Outro')], max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
