# Generated by Django 4.2.1 on 2023-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_checkin_employee_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
