# Generated by Django 4.2.1 on 2023-06-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='finger_print',
            field=models.CharField(max_length=150),
        ),
    ]
