# Generated by Django 4.2.1 on 2023-06-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_finger_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(default=22, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
