# Generated by Django 4.2.1 on 2023-06-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_checkin_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
    ]
