# Generated by Django 4.2.1 on 2023-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_checkin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
