# Generated by Django 4.2.1 on 2023-07-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_function_employee_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='head',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=50),
        ),
    ]
