# Generated by Django 4.2.1 on 2023-07-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_employee_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='function',
            new_name='assignment',
        ),
    ]
