# Generated by Django 4.2.1 on 2023-07-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_function_department_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='finger_print',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
