# Generated by Django 4.2.1 on 2023-07-15 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0017_alter_message_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dapartments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="head",
            field=models.CharField(
                choices=[("SIM", "Sim"), ("NAO", "Não")], default="NAO", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="read",
            field=models.BooleanField(),
        ),
    ]
